name: Tests
on:
  push:
    branches:
      - '**'
jobs:
  test:
    # needs: lint
    strategy:
      matrix:
        ckan-base-version: [2.9]
        ckan-version: [py3.9]
        solr-version: [solr8]
      fail-fast: false

    name: CKAN ${{ matrix.ckan-base-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-base-version }}-${{ matrix.ckan-version }}
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-base-version }}-${{ matrix.solr-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-base-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v4
    - name: Install CURL
      run: apk install curl -y
    - name: Install requirements
      run: |
        pip install -r dev-requirements.txt
        pip install -e .
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
        # Install ckanext-berlin_dataset_schema
        git clone https://github.com/berlinonline/ckanext-berlin_dataset_schema
        pip install -e ckanext-berlin_dataset_schema
        pip install -r ckanext-berlin_dataset_schema/requirements.txt
        # Install ckanext-dcat
        git clone https://github.com/ckan/ckanext-dcat
        pip install -e ckanext-dcat
        pip install -r ckanext-dcat/requirements.txt
    - name: Setup extension (CKAN >= 2.9)
      run: |
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.dcatde_berlin --cov-report=xml --cov-append --disable-warnings ckanext/dcatde_berlin/tests
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov